# Generated by Django 5.1.5 on 2025-08-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField(auto_created=True)),
                ('approved_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('Department of Building Economics', 'Department of Building Economics'), ('Department of Interior Designs', 'Department of Interior Designs'), ('Department of Bussiness studies', 'Department of Bussiness studies'), ('Department of Environmental Science and Management', 'Department of Environmental Science and Management'), ('Department of Architecture', 'Department of Architecture'), ('Department of Land Management and Valuation', 'Department of Land Management and Valuation'), ('Department of Geospatial Sciences and Technology', 'Department of Geospatial Sciences and Technology'), ('Department of Urban and Regional Planning', 'Department of  Urban and Regional Planning'), ('Department of Civil and Environmental Engineering', 'Department of Civil and Environmental Engineering'), ('Department of Computer Systems and Mathematics', 'Department of Computer Systems and Mathematics'), ('Department of Economics and Social Studies', 'Department of Economics and Social Studies')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], default='unknown', max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.department')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.course')),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.department')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.CharField(choices=[('R1(#120)', 'R1(#120)'), ('R3(#120)', 'R3(#120)'), ('R4(#120)', 'R4(#120)'), ('R5(#35)', 'R5(#35)'), ('R11(#84)', 'R11(#84)'), ('R12(#81)', 'R12(#81)'), ('R13(#84)', 'R13(#84)'), ('R14(#84)', 'R14(#84)'), ('R15(#50)', 'R15(#50)'), ('R17(#48)', 'R17(#48)'), ('R18(#80)', 'R18(#80)'), ('R19(#80)', 'R19(#80)'), ('R20(#70)', 'R20(#70)'), ('R21(#48)', 'R21(#48)'), ('R22(#48)', 'R22(#48)'), ('R23(#70)', 'R23(#70)'), ('R24(#70)', 'R24(#70)'), ('R25(#24)', 'R25(#24)'), ('R29(#104)', 'R29(#104)'), ('R38 + 39(#120)', 'R38 + 39(#120)'), ('R44(#64)', 'R44(#64)'), ('R45(#80)', 'R45(#80)'), ('R46(#72)', 'R46(#72)'), ('R51(#60)', 'R51(#60)'), ('R52(#60)', 'R52(#60)'), ('R53(#70)', 'R53(#70)'), ('R54(#60)', 'R54(#60)'), ('R55(#130)', 'R55(#130)'), ('R56(#130)', 'R56(#130)'), ('57(#130)', '57(#130)'), ('R58(#130)', 'R58(#130)'), ('R59(#50)', 'R59(#50)'), ('R60(#50)', 'R60(#50)'), ('R61(#80)', 'R61(#80)'), ('R62(#130)', 'R62(#130)'), ('R63(#130)', 'R63(#130)'), ('R64(#50)', 'R64(#50)'), ('R65(#50)', 'R65(#50)'), ('R66(#80)', 'R66(#80)'), ('R67(#130)', 'R67(#130)'), ('R68(#130)', 'R68(#130)'), ('R69(#50)', 'R69(#50)'), ('R70(#50)', 'R70(#50)'), ('R71(#82)', 'R71(#82)'), ('R72Venue(#82)', 'R72Venue(#82)'), ('R73(#82)', 'R73(#82)'), ('R74(#82)', 'R74(#82)'), ('R75(#82)', 'R75(#82)'), ('R76(#313)', 'R76(#313)'), ('R50-LAB', 'R50-LAB'), ('R49-LAB', 'R49-LAB'), ('R31-LAB', 'R31-LAB'), ('EE LAB - LAB2', 'EE LAB - LAB2'), ('R32-LAB', 'R32-LAB'), ('R33-LAB', 'R33-LAB'), ('R34-LAB', 'R34-LAB'), ('Experimental Hall - Hall', 'Experimental Hall - Hall'), ('ARCH WORKSHOP - WORKSHOP', 'ARCH WORKSHOP - WORKSHOP')], max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.lecturer')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Teaching Timetable', 'Teaching Timetable'), ('Examination Timetable', 'Examination Timetable')], max_length=255)),
                ('semister', models.CharField(choices=[('Teaching Timetable', 'Teaching Timetable'), ('Examination Timetable', 'Examination Timetable')], max_length=255)),
                ('date', models.DateField()),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.course')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.department')),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.lecturer')),
                ('programme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.programme')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ardhiUniversity.room')),
            ],
        ),
    ]
