# Generated by Django 5.1.5 on 2025-08-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardhiUniversity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('cs', 'cs'), ('cnice', 'cnice'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], default='unknown', max_length=255),
        ),
    ]
